### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by colemickens** [theia-ide/theia-rust-extension#2]

**Comment by svenefftinge** [comment]
I added the .travis and activated the build https://travis-ci.org/theia-ide/theia-rust-extension

**Comment by colemickens** [comment]
Thanks @svenefftinge. I'm seeing it failing:

```
error Command "publish:next" not found.
```

I'll poke around and see if it's a matter of updating package.json for Theia plugins, or something else. Any hints are welcome though.

Thanks again

**Comment by colemickens** [comment]
I think https://github.com/theia-ide/theia-rust-extension/pull/3 should fix it and get it published.

**Comment by marcdumais-work** [comment]
The publish still failed: 
```
lerna ERR! publish Ran out of retries while publishing @theia/rust Error: Command failed: yarn publish --tag next --new-version 0.4.0-next.9956f671
lerna ERR! publish error An unexpected error occurred: "Can't answer a question unless a user TTY".
```

https://travis-ci.org/theia-ide/theia-rust-extension

**Comment by colemickens** [comment]
I am neither an npm nor yarn expert.

@svenefftinge Does the first publish need to be done interactively, maybe?

**Comment by marcdumais-work** [comment]
>Does the first publish need to be done interactively, maybe?

That's a good theory, I can try a manual publish and see what happens

**Comment by marcdumais-work** [comment]
update: At first I could not publish locally either, using ```yarn```. However the error message I got was different: 
```
lerna ERR! Error: Command failed: yarn publish --tag next --new-version 0.4.0-next.9956f671
lerna ERR! error An unexpected error occurred: "https://registry.npmjs.org/@theia%2frust: You must sign up for private packages".
```

I think we have seen this before, and this went away after I published using npm:  
```npm publish --access=public``` 

I published a ```latest 0.3.10``` version and a ```next```. 

Now locally I can successfully publish a ```next``` version by running  ```yarn run publish:next``` locally. However the Travis job still fails with the same error message, hinting that the publish is in interactive mode. I have not seen that at all locally, before or after I published successfully. I suspect it's an authentication issue. I noticed that the yarn version we have setup for this is quite old. I'll try to update it and see what happens.

**Comment by marcdumais-work** [comment]
More info now with updated yarn. It looks like an npm auth token [problem](https://travis-ci.org/theia-ide/theia-rust-extension/jobs/401108592#L825):

![image](https://user-images.githubusercontent.com/25749063/42405005-9b552fda-815d-11e8-8b15-fba7f329878b.png)

**Comment by marcdumais-work** [comment]
I generated a fresh npm token to replace the current one in .travis.yml. 

The publish of ```next``` now succeeds: https://travis-ci.org/theia-ide/theia-rust-extension/builds/401129077#L820
